<p>I always used the following code to access Google contacts:</p>  <pre><code>import gdata.contacts.service gd_client = gdata.contacts.service.ContactsService() gd_client.ClientLogin('xxxxxxxx', 'xxxxxxxx') query = gdata.contacts.service.ContactsQuery() query.max_results = 10000 feed = gd_client.GetContactsFeed(query.ToUri()) print feed </code></pre>  <p>However, I am now getting the following <code>Login required</code> error:</p>  <pre><code>Traceback (most recent call last):   File "./1.py", line 10, in &lt;module&gt;     feed = gd_client.GetContactsFeed(query.ToUri())   File "/usr/lib/python2.7/site-packages/gdata/contacts/service.py", line 103, in GetContactsFeed     return self.Get(uri, converter=gdata.contacts.ContactsFeedFromString)   File "/usr/lib/python2.7/site-packages/gdata/service.py", line 1107, in Get     'reason': server_response.reason, 'body': result_body} gdata.service.RequestError: {'status': 401, 'body': '&lt;?xml version="1.0" encoding="UTF-8"?&gt;\n&lt;errors xmlns="http://schemas.google.com/g/2005"&gt;\n &lt;error&gt;\n  &lt;domain&gt;GData&lt;/domain&gt;\n  &lt;code&gt;required&lt;/code&gt;\n  &lt;location type="header"&gt;Authorization&lt;/location&gt;\n  &lt;internalReason&gt;Login Required&lt;/internalReason&gt;\n &lt;/error&gt;\n&lt;/errors&gt;\n', 'reason': 'Unauthorized'}  </code></pre>  <p>What am I doing wrong? I failed to find a solution in Google, yet I found someone saying that some similar code is deprecated.</p>  <p>Thanks!</p>  <p>L.</p>