<p>i have a problem when a CustomUser is used.</p>  <p>apps.accounts.MyUser defines a relathionship (ForeignKey) to<br> apps.registro.models.InstitucionEducativa. But, when runserver is executed, it shows me the following error : </p>  <p><code>apps.accounts.MyUser.school: (fields.E300) Field defines a relation with model 'apps.registro.models.InstitucionEducativa', which is either not installed, or is abstract.</code></p>  <p>My settings.INSTALLED_APPS is equal to :</p>  <pre><code>DJANGO_APPS = (     PACKAGE_NAME_GRAPPELLI,     PACKAGE_NAME_FILEBROWSER,     'django.contrib.admin',     'django.contrib.auth',     'django.contrib.contenttypes',     'django.contrib.sessions',     'django.contrib.messages',     'django.contrib.staticfiles',     'django.contrib.sites',     'django_comments', )  LOCAL_APPS = (     'apps.registro',     'apps.accounts',     'apps.pages',     'apps.core',     'apps.conf',     'apps.utils',     'apps.generic',     'apps.service',     'apps.resource',     'apps.friends',     'apps.forums',     'apps.links',     # 'oauth2_provider',     # 'rest_framework',  )  THIRD_APPS = (     'django_extensions',     'import_export',     'social.apps.django_app.default' ), </code></pre>  <p>Could somebody give me a hand with this? . Thanks!</p>