<p>This is my first time dealing with this type of error. I have a standard django web application where one of my views needs to use a custom module I made. The way I go about debugging is usually to just set breakpoints then see what is happening(Visual Studio 2015 with Python tools).</p>  <p>But when I import my module I get this <code>ValueError: signal only works in main thread</code>. This is caused when my module imports dependencies from other modules. This error only happens when running my app in debug mode(VS F5). If I run my app from cmd in my project folder with <code>python manage.py runserver --nothreading --noreload</code> then it works. But I need to run it in debug mode since I need to see what's going on. </p>  <p>Am I going to be stuck just using print statements to see what' going on or is there a way to get this to work with debugging?</p>  <p>this is the line where it starts going downhill: <code>from bacpypes.core import run, stop</code></p>  <pre><code>Traceback: File "C:\Users\jb.DOM\Desktop\BACnet Modbus\ModbusBACnet\BACnetModbus_WebApp\env\lib\site-packages\django\core\handlers\base.py" in get_response   119.                 resolver_match = resolver.resolve(request.path_info) File "C:\Users\jb.DOM\Desktop\BACnet Modbus\ModbusBACnet\BACnetModbus_WebApp\env\lib\site-packages\django\core\urlresolvers.py" in resolve   368.                     sub_match = pattern.resolve(new_path) File "C:\Users\jb.DOM\Desktop\BACnet Modbus\ModbusBACnet\BACnetModbus_WebApp\env\lib\site-packages\django\core\urlresolvers.py" in resolve   240.             return ResolverMatch(self.callback, args, kwargs, self.name) File "C:\Users\jb.DOM\Desktop\BACnet Modbus\ModbusBACnet\BACnetModbus_WebApp\env\lib\site-packages\django\core\urlresolvers.py" in callback   247.         self._callback = get_callable(self._callback_str) File "C:\Users\jb.DOM\Desktop\BACnet Modbus\ModbusBACnet\BACnetModbus_WebApp\env\lib\site-packages\django\utils\lru_cache.py" in wrapper   101.                     result = user_function(*args, **kwds) File "C:\Users\jb.DOM\Desktop\BACnet Modbus\ModbusBACnet\BACnetModbus_WebApp\env\lib\site-packages\django\core\urlresolvers.py" in get_callable   106.         mod = import_module(mod_name) File "C:\Python27\Lib\importlib\__init__.py" in import_module   37.     __import__(name) File "C:\Users\jb.DOM\Desktop\BACnet Modbus\ModbusBACnet\BACnetModbus_WebApp\app\views.py" in &lt;module&gt;   17. from app import create_bacnet File "C:\Users\jb.DOM\Desktop\BACnet Modbus\ModbusBACnet\BACnetModbus_WebApp\app\create_bacnet.py" in &lt;module&gt;   7. from bacpypes.core import run, stop File "C:\Users\jb.DOM\Desktop\BACnet Modbus\ModbusBACnet\BACnetModbus_WebApp\env\lib\site-packages\bacpypes\__init__.py" in &lt;module&gt;   18. from . import vlan File "C:\Users\jb.DOM\Desktop\BACnet Modbus\ModbusBACnet\BACnetModbus_WebApp\env\lib\site-packages\bacpypes\vlan.py" in &lt;module&gt;   13. from .core import deferred File "C:\Users\jb.DOM\Desktop\BACnet Modbus\ModbusBACnet\BACnetModbus_WebApp\env\lib\site-packages\bacpypes\core.py" in &lt;module&gt;   166.     signal.signal(signal.SIGTERM, stop)  Exception Type: ValueError at /create_bacnet Exception Value: signal only works in main thread </code></pre>