<p>I'm getting an error when running a suds call (I'm using suds-jurko). I've tested this out on a different export and it worked fine. Just for whatever reason the data I'm trying to pull has some issues with and I'm trying to figure out what the exact issue is. I've pulled the data using another method, but there is no column 209, so trying to understand better what is causing that to think that.</p>  <pre><code>    Traceback (most recent call last):   File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/xml/sax/expatreader.py", line 207, in feed     self._parser.Parse(data, isFinal) xml.parsers.expat.ExpatError: reference to invalid character number: line 96835, column 209 </code></pre>  <p>Any thoughts of how to debug this are most welcome.</p>