<p>I'm trying to execute a command via <strong>session.Run()</strong> function over a ssh connection. So far I can successfully execute some commands but on others I keep getting the following error: <strong>"Process exited with: 1. Reason was:  () exit status 1"</strong></p>  <pre><code>func (p *project) connect(config *ssh.ClientConfig) {      log.Printf("Trying connection...\n")      conn, err := ssh.Dial("tcp", fmt.Sprintf("%s:%s", p.hostname.name, p.port.name), config)     checkError("Failed to dial: ", err)     log.Printf("Connection established.\n")      for step := range p.typ.program.setup {         p.install(step, conn)     } }  func (p *project) install(step int, conn *ssh.Client) {     session, err := conn.NewSession()     checkError("Failed to build session: ", err)     defer session.Close()      var stdoutBuf bytes.Buffer     session.Stdout = &amp;stdoutBuf      log.Printf("Executing command: %s", p.typ.program.setup[step])      if err := session.Run(p.typ.program.setup[step]); err != nil {         log.Println(session.Stdout)         log.Fatal("Error on command execution", err.Error())     } }   // That would be an example of a command which returns me an error // "cd ~/www/www/ &amp;&amp; git commit -m 'on the beginning was the commit'" // That comes inside a slice on p.typ.program.setup accessed by the step(index). </code></pre>  <p>The command output (session.Stdout) is the one i expect:</p>  <pre><code> "# On branch master nothing to commit, working directory clean" </code></pre>  <p>And just to note I already tried to execute the command directly on the console and it works just fine.</p>  <p>So, the code seems to be okay, the command ran on the remote but I still have an error no matter what.</p>  <p>Does anyone have a clue about why is that happening?</p>  <p>Thanks in advance.</p>