<p>I'm trying to write a small program where I came to the following problem:</p>  <p>In one of my methods I have the following piece of code</p>  <pre><code>try{     rootHuman = Human.load(scanner.next()); }catch(FileNotFoundException f){     //Missing Code               } </code></pre>  <p>where I try to catch a FileNotFoundException. So looking at the function call from Human.load() we have this piece of code</p>  <pre><code>public static Human load(String filename){     try{         Human human;         FileInputStream fileIn = new FileInputStream(filename);         ObjectInputStream in = new ObjectInputStream(fileIn);         human = (Human) in.readObject();         in.close();         fileIn.close();         return human;     }catch(IOException i){         i.printStackTrace();         return null;     }catch(ClassNotFoundException c){         c.printStackTrace();         return null; } </code></pre>  <p>also when trying to catch the FileNotFoundException here I get the same problem. My Problem is that the compiler tells me that this exception is never thrown, but when I execute the code I can obviously get a  FileNotFoundException when the input from scanner.next() is a filename that doesn't exist. I'm kind of pointless here so any piece of advice is very much welcome.</p>  <p>Thanks in advance</p>