<p>I am trying to delete a mass amount of records from my database. My destroy_all keeps getting stopped when a callback fails to destroy a record because of <code>ActiveRecord::RecordNotFound</code>. I want to skip the callbacks when the error <code>ActiveRecord::RecordNotFound</code> occurs on records that the callback is trying to delete. </p>  <p>All User records belong to school via a UserSchool relation. I am trying to delete all User Records where the <code>school_id</code>: 74 is present in any UserSchool record. </p>  <pre><code>user_ids = UserSchool.where(school_id: 74).map(&amp;:user_id) User.where(id: user_ids).destroy_all   </code></pre>  <p>The result is: </p>  <pre><code>ActiveRecord::RecordNotFound: Couldn't find Comment with 'id'=17 </code></pre>  <p>I want to skip over that error and continue destroying User records. How can I rescue here?</p>